# Generated by Django 4.2 on 2024-04-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_formquestion_remove_formsubmission_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formquestion',
            options={'verbose_name': 'Форма заявки вопроса', 'verbose_name_plural': 'Форма заявки вопроса'},
        ),
    ]
