# Generated by Django 4.2 on 2024-04-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='flag_photos/', verbose_name='Флаг'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название страны'),
        ),
    ]
