# Generated by Django 4.2 on 2024-04-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammember', '0002_alter_teammember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
