# Generated by Django 4.2 on 2024-04-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsubmission',
            name='comment',
        ),
    ]
