# Generated by Django 4.2 on 2024-04-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_formsubmission_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
