# Generated by Django 4.2 on 2024-04-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_formquestion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flag_photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'направление',
                'verbose_name_plural': 'направление',
            },
        ),
    ]
