# Generated by Django 4.2 on 2024-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Заработок')),
                ('start_date', models.DateField(verbose_name='Начало дня работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='job_images/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Актуальная работа',
                'verbose_name_plural': 'Актуальные работы',
            },
        ),
    ]
